import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSync } from "esbuild";
import {
  PENTOVIDEO_RUNTIME_ARTIFACTS,
  PENTOVIDEO_RUNTIME_CONTRACT,
  loadPentovideoRuntimeSource,
} from "../src/inline-scripts/pentovideo";

const thisDir = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(thisDir, "../dist");
const iifePath = resolve(distDir, PENTOVIDEO_RUNTIME_ARTIFACTS.iife);
const esmPath = resolve(distDir, PENTOVIDEO_RUNTIME_ARTIFACTS.esm);
const manifestPath = resolve(distDir, PENTOVIDEO_RUNTIME_ARTIFACTS.manifest);

const runtimeSourceRaw = loadPentovideoRuntimeSource();
if (runtimeSourceRaw === null) {
  throw new Error("Cannot build runtime artifact: entry.ts not found at expected path");
}
const runtimeSource = `${runtimeSourceRaw}\n`;
const runtimeSha256 = createHash("sha256").update(runtimeSource, "utf8").digest("hex");
const buildId = process.env.PENTOVIDEO_RUNTIME_BUILD_ID?.trim() || "dev";
const runtimeEntryPath = resolve(thisDir, "../src/runtime/entry.ts");
const esmBuild = buildSync({
  entryPoints: [runtimeEntryPath],
  bundle: true,
  write: false,
  platform: "browser",
  format: "esm",
  target: ["es2020"],
  minify: true,
  legalComments: "none",
});
const esmSource = `${esmBuild.outputFiles[0]?.text ?? ""}\n`;

const manifest = {
  version: process.env.PENTOVIDEO_RUNTIME_VERSION?.trim() || "0.1.0",
  buildId,
  sha256: runtimeSha256,
  artifacts: {
    iife: PENTOVIDEO_RUNTIME_ARTIFACTS.iife,
    esm: PENTOVIDEO_RUNTIME_ARTIFACTS.esm,
  },
  contract: PENTOVIDEO_RUNTIME_CONTRACT,
};

mkdirSync(distDir, { recursive: true });
writeFileSync(iifePath, runtimeSource, "utf8");
writeFileSync(esmPath, esmSource, "utf8");
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

// ── Generate src/generated/runtime-inline.ts ──────────────────────────────
// This file is compiled by tsc into dist/ and provides the production-safe
// getPentovideoRuntimeScript() that returns the IIFE as a string constant —
// no esbuild, no file I/O, no import.meta.url arithmetic.
const generatedDir = resolve(thisDir, "../src/generated");
mkdirSync(generatedDir, { recursive: true });
const inlineModulePath = resolve(generatedDir, "runtime-inline.ts");
const escapedSource = JSON.stringify(runtimeSourceRaw);
writeFileSync(
  inlineModulePath,
  [
    "// AUTO-GENERATED by scripts/build-pentovideo-runtime-artifact.ts — do not edit",
    `const RUNTIME_IIFE: string = ${escapedSource};`,
    "",
    "/**",
    " * Returns the pre-built pentovideo runtime IIFE as a string constant.",
    " * This is the production-safe path: no esbuild, no file I/O,",
    " * no import.meta.url arithmetic.",
    " */",
    "export function getPentovideoRuntimeScript(): string {",
    "  return RUNTIME_IIFE;",
    "}",
    "",
  ].join("\n"),
  "utf8",
);

console.log(
  JSON.stringify({
    event: "pentovideo_runtime_artifacts_generated",
    buildId,
    distDir,
    iifePath,
    esmPath,
    manifestPath,
    inlineModulePath,
    sourceBytes: Buffer.byteLength(runtimeSource, "utf8"),
    esmBytes: Buffer.byteLength(esmSource, "utf8"),
    sha256: runtimeSha256,
  }),
);
